### ISSUE TITLE
O link que estava direcionado para o correio não funciona mais.

### ISSUE THREAD

**Issue by cristianosamorim** [wrparra/Correios.NET#1]
Olá amigo, o link que você colocou nesse código não funciona mais, foi desativado pelo correio, o novo link é esse => http://sro.micropost.com.br/consulta.php?objetos=codigodoobjeto

[]´s

Cristiano

**Comment by wrparra** [comment]
Olá Cristiano, muito obrigado pelo aviso. Vou checar.
[]´s
