### ISSUE TITLE
Consulta CEP - Retorno NULL

### ISSUE THREAD

**Issue by costaalvesgabriel** [wrparra/Correios.NET#11]
Utilizo a biblioteca a bom tempo, mas hoje quando é feita a consulta por qualquer CEP, está retornando NULL.
![correios net](https://github.com/wrparra/Correios.NET/assets/85899283/39b123f2-e173-45ca-89f4-58287ba34214)

**Comment by wrparra** [comment]
Olá. Infelizmente os Correios implementaram checagem via Captcha e esta biblioteca não funciona mais.
Mas fique a vontade para fazer fork e contribuir com outra implementação de consulta de CEP.
