### ISSUE TITLE
Utilizar WebServices do Correio ao invés de parser

### ISSUE THREAD

**Issue by brunobertechini** [wrparra/Correios.NET#2]
Não seria melhor utilizar o webservice que o correio disponibiliza para esta consulta e demais outras operações ?

O que acha ?

Bruno

**Comment by wrparra** [comment]
Olá Bruno, este projeto é um estudo de como utilizar os serviços dos correios por meio de parsers. 
Ele surgiu na época em que os correios não disponibilizavam os dados via apis.
Pode ser que futuramente eu implemente a consulta via APIs, mas hoje não é o foco.
At.,
Wellington

**Comment by brunobertechini** [comment]
Estou implementando uma lib usando webservices do correio

Teria interesse em criarmos com outro nome e sermos contributors?

Eu chamei de Correios4Net

Bruno

**Comment by wrparra** [comment]
Não, obrigado.
