### ISSUE TITLE
Código de rastreio não encontrado

### ISSUE THREAD

**Issue by rogeriozanardo** [wrparra/Correios.NET#9]
Desde ontem, todo e qualquer código de rastreio que consulto está retornando a exception "Código da encomenda/pacote não foi encontrado..", porém consultando o mesmo código de rastreio diretamente no site dos correios são exibidas todas as informações.

Alguém sabe se houve alguma alteração no ambiente?

**Comment by lfelipebarbieri** [comment]
Ola, 
Conseguiu de alguma maneira resolver o problema da exception "Código da encomenda/pacote não foi encontrado.." ?

**Comment by wrparra** [comment]
Os Correios mudou a API deles para consulta de Encomendas e está utilizando Captcha para evitar consultas de terceiros.
A alternativa seria utilizar outra API, mas por eqto não tenho idéia do que fazer. Sugestões e implementações serão bem vindas. Pois no momento tbm estou sem tempo para correções.

**Comment by wrparra** [comment]
Nova versão disponível.
